-- ============================================================
-- PAGEX — Community Notes Migration
-- Feature 1: Community PDF Upload
-- ============================================================

CREATE TABLE IF NOT EXISTS community_notes (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  subject TEXT NOT NULL,
  semester TEXT,
  unit TEXT,
  storage_path TEXT NOT NULL,
  file_name TEXT NOT NULL,
  file_size BIGINT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for performant filtering and searching
CREATE INDEX IF NOT EXISTS idx_community_notes_user ON community_notes(user_id);
CREATE INDEX IF NOT EXISTS idx_community_notes_status ON community_notes(status);
CREATE INDEX IF NOT EXISTS idx_community_notes_subject ON community_notes(subject);
CREATE INDEX IF NOT EXISTS idx_community_notes_created_at ON community_notes(created_at DESC);

-- Trigger to maintain updated_at
DROP TRIGGER IF EXISTS community_notes_updated_at ON community_notes;
CREATE TRIGGER community_notes_updated_at
  BEFORE UPDATE ON community_notes
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- Security model:
-- 1. Direct client INSERT/UPDATE/DELETE is BLOCKED on community_notes.
--    All uploads, status modifications, and deletions must go through Express.
-- 2. Authenticated users can view approved notes.
-- 3. Uploaders can view their own notes (including pending and rejected).
-- 4. Admins can view all notes.
-- ============================================================

ALTER TABLE community_notes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read approved community notes"
  ON community_notes FOR SELECT
  TO authenticated
  USING (status = 'approved');

CREATE POLICY "Users can read own community notes"
  ON community_notes FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY "Admins can read all community notes"
  ON community_notes FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- Storage bucket note:
-- Create private bucket 'community-notes' in Supabase Storage.
-- All access to PDFs in this bucket requires short-lived signed URLs generated by the backend.
